services:
  data_api:
    image: data_api:latest
    container_name: data_api_container
    build: 
      context: ./src
      dockerfile: Dockerfile
    environment:
      - CSV_FILE_PATH=/app/app/data.csv
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./src/data.csv:/app/app/data.csv:ro
  
  docs:
    image: docs:latest
    container_name: docs_container
    build: 
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://service_api:8000/docs

  auth_service:
    image: auth_service:latest
    container_name: auth_service_container
    build: 
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "9090:8000"
